### ISSUE TITLE
API改变了，更新cookies后返回的数据

### ISSUE THREAD

**Issue by chen-jian350** [Carmenliukang/image_search_products#1]
data: {'rgv587_flag': 'sm', 'url': '/api/upload.api/_____tmd_____/punish?x5secdata=xb2fc6b184506b96045f1580ff54c1a1bd1638510935a1855144138a-1029588677abazc2ak1877258025a__bx__stream-upload.taobao.com%3A443%2Fapi%2Fupload.api&x5step=2'}

**Comment by Carmenliukang** [comment]
api v2
